### ISSUE TITLE
Divers 

### ISSUE THREAD

**Issue by AdGui** [jomuller/jomuller.github.io#1]
Sympa ton blog ! (malheureusement on ne peut pas laisser de commentaires...)

Pour ce qui est des cartes dans R j'ai eu l'occasion de m'attarder sur la question et je conseillerai plutôt d'utiliser GEOFLA comme source (plutôt que gadm) : c'est l'ensemble des découpages administratifs français (gratuit jusqu'à la commune) en différents formats avec des caractéristiques de base intégrées (population, centroïde, chef-lieu,...), maintenu par l'IGN.
Personnellement je prends les shapefile, ils sont assez faciles à importer/manipuler dans R.

Et pour la représentation, ggplot est nettement plus modulable que map, spplot ou ggmap. Mais j'ai découvert leaflet assez récemment et là c'est encore un niveau au dessus de ggplot ! Surtout niveau interactivité, pour les cartes statiques ggplot suffit.

Sinon je pense qu'il y'a un soucis dans ton code, la côte d'or ne peut pas être plus peuplée que Paris !

**Comment by jomuller** [comment]
Hello! Merci pour tes commentaires! Je suis content d'avoir au moins un lecteur :-)
J'avais la contrainte de ne pas utiliser ggplot dans ce travail. Je suis d'ailleurs allé un peu plus loin sur mes représentations cartographiques car j'y ajoute les DOM joliment. Je connais aussi leafleft mais il est encore un peu jeune mais vraiment cool pour créer rapidement une carte. J'utilise aussi GEOFLA de l'IGN en réalité. Pour ce billet, je voulais juste répliquer une méthode connue. 

Et en effet il y a un soucis dans mon code, il faut que je le corrige! Merci. Si ça tente de travailler ensemble à l'occasion sur un sujet, ça sera avec plaisir.

**Comment by AdGui** [comment]
Plus tu publieras de contenus interessants plus tu auras de lecteurs !

Je n'ai pas trop vu le côté rapide de leaflet mais probablement parce que je passe par l'intermédiaire de R (je n'ai aucune compétence en javascript).

Je suis tout à fait partant pour travailler ensemble à l'occasion. Mais pour encore quelques temps je suis assez limité niveau temps : je dois me cantonner à SAS pour le M2 de l'interregion... La carte que j'ai faite sur les ECN n'était qu'un petit interlude pour ne pas trop perdre en R (grace à SAS j'ai tendance à mettre ";" à chaque fin de ligne...).
